# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  waxseal_job:
    runs-on: ubuntu-latest
    name: Waxseal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Waxseal it
        uses: boardfish/waxseal@v1.0.2
        id: waxseal
        with:
          input_directory: 'markdown'     # Takes .md files from ./in...
          output_directory: 'build'   # ...and compiles them to PDFs in ./out...
          template_file: 'template.tex' # ...using the template at template.tex.
